### ISSUE TITLE
AWS IoT now requires a short clientId

### ISSUE THREAD

**Issue by isamu-tanaka** [mendix/MxAwsIotConnector#1]
AWS IoT worked with this module before but it now requires a short clientId.
To make it enable, my changes are:

MqttConnector.java

            // String clientId = "MxClient_" + xasId + "_" + hostname + "_" + brokerHost + "_" + brokerPort;
            String clientId = "bluemix-receiver";

IotThing.java

            // DefaultClientid("DefaultClientid");
            DefaultClientid("bluemix-receiver");

This solution is just temporal.  It is much better to accept clientId for setting from Mendix widget.

**Comment by simo101** [comment]
Should be fixed with the latest update: #3
